### ISSUE TITLE
Fix leaf nodes in directed graphs

### ISSUE THREAD

**Issue by ella-clement** [LCB0B/adaptive_cut#7]
https://github.com/LCB0B/adaptive_cut/blob/86e5660c64d3d811912834024c158a3817f964e3/AdaptiveCut/LinkClustering.py#L230C1-L230C64

When a node has no successors it doesn't get added to `self.adj`, however it still may be an element of another node's successors (only an issue in the directed case). This means that when we call `similarities_weighted_directed`, there can be an error in the lines linked above where inclusive[ni] or inclusive[nj] doesn't exist.

**Comment by LCB0B** [comment]
fixed
